# Generated by Django 5.2.4 on 2025-07-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User ', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('host', 'Host'), ('security', 'Security')], default='host', max_length=20, verbose_name='User  Role'),
        ),
        migrations.AlterField(
            model_name='visitorsetting',
            name='default_checkin_duration',
            field=models.PositiveIntegerField(default=4, verbose_name='Default Check-in Duration (hours)'),
        ),
    ]
