# Generated by Django 5.2.4 on 2025-07-15 11:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='visitors.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='visitors.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_es',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name_es',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_en',
            field=models.TextField(blank=True, null=True, verbose_name='Visit Purpose'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_es',
            field=models.TextField(blank=True, null=True, verbose_name='Visit Purpose'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Visit Purpose'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='action_en',
            field=models.CharField(choices=[('pre_register', 'Pre-Registered'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('blacklisted', 'Blacklisted'), ('notification_sent', 'Notification Sent')], max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='action_es',
            field=models.CharField(choices=[('pre_register', 'Pre-Registered'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('blacklisted', 'Blacklisted'), ('notification_sent', 'Notification Sent')], max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='action_fr',
            field=models.CharField(choices=[('pre_register', 'Pre-Registered'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('blacklisted', 'Blacklisted'), ('notification_sent', 'Notification Sent')], max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='details_en',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='details_es',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='details_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Branch Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('receptionist', 'Receptionist'), ('host', 'Host'), ('security', 'Security')], default='host', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma-separated options for select/radio/checkbox', null=True, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='expected_arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Arrival Time'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driver_license', 'Driver License'), ('other', 'Other')], max_length=30, null=True, verbose_name='ID Type'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='action',
            field=models.CharField(choices=[('pre_register', 'Pre-Registered'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('blacklisted', 'Blacklisted'), ('notification_sent', 'Notification Sent')], max_length=20, verbose_name='Action'),
        ),
    ]
