# Generated by Django 5.2.4 on 2025-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_alter_branch_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_kis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_title_kis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='company_kis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='first_name_kis',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='last_name_kis',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='purpose_kis',
            field=models.TextField(blank=True, null=True, verbose_name='Visit Purpose'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='action_kis',
            field=models.CharField(choices=[('pre_register', 'Pre-Registered'), ('check_in', 'Checked In'), ('check_out', 'Checked Out'), ('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('blacklisted', 'Blacklisted'), ('notification_sent', 'Notification Sent')], max_length=20, null=True, verbose_name='Action'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='details_kis',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
    ]
