# Generated by Django 5.2.4 on 2025-07-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_customuser_department_kis_customuser_job_title_kis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='action_en',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='action_es',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='action_fr',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='action_kis',
        ),
    ]
