# Generated by Django 5.2.4 on 2025-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_remove_customuser_department_af_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='expected_duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Expected Duration'),
        ),
    ]
