# Generated by Django 5.2.4 on 2025-08-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_visitor_latitude_visitor_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='expected_duration',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='longitude',
        ),
    ]
