# Generated by Django 5.2.4 on 2025-08-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_realtimenotificationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RealtimeNotificationLog',
        ),
    ]
